export const MOCK_RESPONSE = `
Okay, let's see. The position is move 9 for White, and the game is in check. Wait, the board shows that the black queen is at d7 (since on the 7th rank, it's p p p p q N p p). But the check here—I need to confirm where the check comes from. The FEN is r1b1kb1r/ppppqNpp/8/8/6n1/2N5/PPPP1PPP/R1BQKB1R w KQkq - 1 9. Hmm, the current position might have a check from a black piece. Let me visualize again.

Wait, the ⚠️ says IN CHECK. So White's king is in check. Looking at the 1st rank: R . B Q K B . R. So the White king is at e1. The Black queen is at d7. How is the king in check? Maybe a diagonal from d8 to e7 to f6... but White's king is on e1. Let me check pieces that could give check. Maybe the Black queen can move to a square that attacks the king. Oh, wait—the Black queen is on d7. The king is on e1. The queen can't attack diagonally from d7 to e1. Maybe the knight is giving check? The Black knight is on g4. A knight on g4 can attack f2 or e3, but the king is at e1. Wait, maybe the check comes from another piece. The Black bishop is on c8, but that's on a8. Maybe there's a different check. Wait, maybe the Black queen is moving somewhere else? Wait the FEN is given. Let me parse the FEN correctly.

The FEN is r1b1kb1r/ppppqNpp/8/8/6n1/2N5/PPPP1PPP/R1BQKB1R. So the position is as follows:

8th rank: r1b1kb1r → rook, bishop, knight, king, bishop, rook? No, that doesn't make sense. Wait, the 8th rank in standard notation is in the order a to h. So r1b1kb1r would mean a8-rook, b8-bishop, c8-knight, d8-king, e8-bishop, f8-rook. But that's White's 8th rank, but since it's Black to move in the check, maybe the king is in check from another piece. Wait, the position is as the user visualized it. The user's board shows that on the 1st rank (White's side), it's R . B Q K B . R. So the king is at e1. The Black queen is on d7. The White king is in check—how? Maybe there's a Black rook or bishop attacking e1. Looking at the board:

Black bishop on f8 (from the 8th rank: R . B Q K B . R? Wait the user's board for the 1st rank (White's pieces) is R . B Q K B . R. So a1=R, c1=B, d1=Q, e1=K, f1=B, h1=R. So the Black queen is on d7. The White king at e1. The check would come from a Black bishop if one is on a diagonal. Let's see: Black bishops are on c8 and f8. The Black king is on d8? Or maybe the user's board has the king on d8. Wait, the user's board for rank 1 is R . B Q K B . R. So White's king is at e1, queen at d1. On the 8th rank (Black's side), the king is at e8? Wait the board shows for 8th rank: r1b1kb1r. Wait, the standard notation starts from the 8th rank as per FEN. The user's board shows the 8th rank as e8 having k, but according to the FEN, maybe the user has the Black pieces on the 8th rank. Let me parse the FEN again.

FEN: r1b1kb1r/ppppqNpp/8/8/6n1/2N5/PPPP1PPP/R1BQKB1R. The first part is the board state: from rank 8 to 1 (so Black's side first). So the 8th rank: r (rook on a8), then 1 (empty), b (bishop on b8), 1 (empty), k (Black king on c8), b (bishop on d8), 1 (empty), r (rook on h8)? Wait that seems off. Wait FEN for the position:

Starting from the 8th rank: r1b1kb1r → 1st row from top (Black's side). So, a8: r, b8: 1 (empty), c8: b, d8: 1 (empty), e8: k, f8: b, g8: 1 (empty), h8: r. Then the 7th rank is p p p p q A N p p (A is K? Wait original board in the user's visualization for the 7th rank is p p p p q N p p. So Black on the 7th rank (2nd row in the user's diagram) has a and b files with pawns, then c8? Wait maybe there's confusion in how the user laid out the board. The user's diagram shows:

8 | r  .  b  .  k  b  .  r |
7 | p  p  p  p  q  N  p  p |
6 | .  .  .  .  .  .  .  . |
5 | .  .  .  .  .  .  .  . |
4 | .  .  .  .  .  .  n  . |
3 | .  .  N  .  .  .  .  . |
2 | P  P  P  P  .  P  P  P |
1 | R  .  B  Q  K  B  .  R |

So the 8th rank (from Black's perspective) has Black's pieces as rook(a8), empty(b8), bishop(c8), empty(d8), king(e8), bishop(f8), empty(g8), rook(h8). Wait, the king is on e8, which is normal. Wait, the 7th rank is Black pawns on a7, b7, c7, d7, e7 has q (queen), f7 is N (knight), g7 is p, h7 is p. But that seems like Black's queen is on e7. The 7th rank is p p p p q N p p, so that would be Black's pawns, queen at e7, knight at f7. So White's king is on e1, in the 1st rank. But how is White in check? The only possible check would be from Black's queen on e7. Wait, the queen can attack diagonally. From e7 to something like f8, but that's Black's rook. Wait, maybe the check is from the Black queen on e7 to the White king on e1 via a diagonal. Wait, the distance is 7 squares, but the queen can attack that. However, the path must be clear. Let me check. The queen is on e7. If it moves along the e-file, but the king is on e1. So moving the queen from e7 down the e-file to e1. Are there pieces blocking? The 6th and 5th ranks are empty. The 4th rank has a knight on g4? Wait, no, the 4th rank is empty in the user's board—so the queen can move down the e-file to e1. But the White king is on e1. So that's a discovered check.

Wait, but the FEN is r1b1kb1r/ppppqNpp/8/8/6n1/2N5/PPPP1PPP/R1BQKB1R. Let me recheck the board. The Black queen is on e7. The White king is on e1. The e-file is: e8 is k, e7 is q, e6 is ., e5 is ., e4 is ., e3 is ., e2 is P (from rank 2), and e1 is K. So the queen on e7 can attack the king on e1 along the e-file. So the king is in check because the queen is directly in front of it on the e-file. That means White must respond to the check immediately.

Looking at the legal moves provided: [Ne5, Ne4, Ne2, Qe2, Be2]. Wait, but the check is along the e-file. So White's king is on e1, and the check comes from the queen on e7. To get out of check, White has to move the king, block the check, or capture the queen. Since the check is along the e-file, blocking by moving a piece to e2 would block the queen's line of attack. The king can't move to e2 because the queen is at e7, which is attacking e1 and e2 is on the same line. Wait, no—if the queen is on e7 and the king is on e1, the queen can capture the king on e1 if not blocked. So White's king is in check, and the only way to respond is to move the king, capture the queen (unlikely since Queen is attacking e1), or interpose a piece on e2. Because in this case, the queen on e7 can move down to e1 if the path is clear. So blocking on e2 would prevent that.

Looking at the legal moves, White has the option to move Qe2, Be2, Ne2, etc. Let's see which pieces can go to e2. The White queen is on d1. B moves: maybe the bishop can go to e2. The move Be2 would interpose the bishop on e2, blocking the check. Similarly, Qe2 would interpose the queen. Ne2 is a knight on White's side. To find which piece. The White knight is on c3. If the knight moves to e2, that would interpose. The bishop on f1 is on f1; perhaps the king is at e1, and the White has a bishop at f1 which can move to e2. Wait, the bishop is at f1 (as per rank 1: R . B Q K B . R. So f1 is bishop. So Be2 is a legal move. Similarly, Qe2 would move queen from d1 to e2. Ne5 is the knight on c3 going to e5, Ne4 would go to e4, Ne2 to e2.

So the king is in check from e7 (queen) to e1. To block, White can move any piece to e2. The available moves are Ne5, Ne4, Ne2, Qe2, Be2. So Qe2 and Be2 and Ne2 are interposing. Let me check each:

Qe2: The queen is on d1. Moving to e2 would block the queen. Then the queen is defending e2, so the Black queen can't capture her. But that move would protect the king but maybe not the best. Be2: the bishop on f1 can move to e2 via f1 to e2. That also blocks the check and develops the bishop. Ne2: the knight on c3 can move to e2. That blocks the check and develops the knight active. But since the legal moves include all these, which one is correct.

But also, is capturing the queen possible? The Black queen is on e7. The only way for White to capture it is to have a piece move there. But the queen is protected. Let me see the Black's pieces: on e7, the queen is supported by the pawns on d7, f7, etc.? Wait in the diagram, rank 7 (Black's side) has p p p p q N p p. So the queen on e7 is supported by the pawns in d7 and f7. So if White tries to capture it with a knight, for example, the queen would be protected. Alternatively, maybe the knight can capture the queen if it's not protected. Wait, if a White knight is moving from c3 to e4, maybe? But in the legal moves, Ne5 is in the list. So White's king is in check and needs to immediately respond.

So the first step is to identify that the king is in check via the e-file. The only way to respond is to block the line. The moves Qe2, Be2, Ne2, Ne4, Ne5—all of these are from the piece moving to e2 or intercepting. Wait, Ne5 is the knight moving from c3 to e5, which doesn't block the e-file. Ne4 is moving from c3 to e4: which is on the e-file but e4 is between e7 and e1. The queen is at e7, so moving knight to e4 would block a knight. Wait, the queen is at e7, but the knight on c3 can go to e4, which is on the e-file. That would be between e7 and e1. So Ne4 would interpose as well. So all these options are actually interposing pieces. Which one is best?

So the reasoning here is that White must block the e7 queen's line to the king. The possible interposing moves are Ne2, Be2, Qe2, and maybe Ne4 or Ne5? But Ne5 and Ne4 would also block the line? Wait, the queen is at e7. The line of attack is along the e-file. So any piece on e2, e3, e4, e5, e6, or e7 would block. So moving a piece to e2 would block at e2, which is the closest square to the king. But perhaps capturing the queen is better, but the queen is protected. Let's check:

The Black queen is at e7. If White moves a piece to e7 to capture it (like Qxe7 or something), then since the Black queen is protected by the pawn on d7, White can't capture it. So that's not an option. Moving the king? The king can move to d1 or e5, but in the current position, the king is at e1. The king can't move to e5 because that's along the e-file. The king could move to d1, e1, or f1, but under check along the e-file. So the king can't move to any squares along the e-file except if the check is blocked. So the king can move to f1 (if not in check from elsewhere). Let me see if there are other checks. The Black bishop on c8 might also be giving check? The bishop is at c8, so a diagonal to f1 would be c8 to f1. But from the 8th rank, c8 to f1 is the diagonal. So if the bishop is moving from c8 to f1 (Bxf1), but the king is on e1. Wait, the bishop is at c8. Its diagonal is a6, b7, c8, d7, etc., moving towards the White king. If the Black bishop is on c8, the line to the king is along a6-e1? No, the king is on e1. The bishop on c8 can attack e2 through the diagonal c8 to e2, f1 (but f1 is where the White bishop is). Wait the bishop on c8 (Black's bishop) would attack along the a6-c8 diagonal. To see if the bishop can attack e1: c8 to e1 is a diagonal. The bishop on c8 can attack e1's square? Wait, c8 to e1 is two squares right and one down. That's not a true diagonal. Wait the correct diagonal for a bishop on c8 is c8, d7, e6, f5, g4, h3, and also b7, which would be another diagonal. The king is on e1. The bishop at c8 can't attack e1. Because to reach e1 from c8, you have to go two squares left and seven up, which is not a valid bishop movement. So the only check is from the queen on e7, which is attacking the king on e1 via the e-file. So White needs to block with a piece on e2, e3, e4, e5, e6, or e7 (but the latter is probably not because the queen is protected). But the king is on e1 and can't move until the check is addressed.

Now, looking at the legal moves provided: [Ne5, Ne4, Ne2, Qe2, Be2]. So each of these moves is a piece attempting to block the check on the e-file.

Qe2: Moving the queen from d1 to e2. This blocks the check but also develops the queen. However, moving the queen to e2 might be a bit out of position. Be2: Moving the bishop from f1 to e2. That would block the queen's line and develop the bishop into a more active position. Ne2: The knight moves from c3 to e2, blocking the check and developing the knight to attack the f4-square (but if the bishop was there). However, the knight's position on e2 may not be as active as the others.

Ne5 (knight from c3 to e5): That's moving the knight away from blocking the line. Similarly, Ne4 is moving the knight to e4, which is between e7 and e1. Wait, because the e-file is vertical, so moving a piece to e4 (which is two squares closer to e7) would still block the check. So Ne5, Ne4, Ne2 are all possible knight moves. If White's knight is on c3, moving to e2, e4, or e5 would all interpose.

Wait, moving to e2 is two squares closer to e1, e4 is one step away. But moving the knight to e2 would block the check. So all three knight moves (Ne5, Ne4, Ne2) interpose. Similarly, Qe2 and Be2. So the first priority is to block the check. Now, which interposition is best?

Qe2 (queen to e2): That would block and develop the queen. However, moving the queen might be suboptimal if there are tactical overreaches. For example, after Qe2, the Black queen on e7 could capture the White queen on e2 if it's not protected. Wait, but the Black queen is on e7, which is the same file. So if White's queen is on e2, and the Black queen is on e7, then if White moves Qe2 and the queen is on e7, she can capture the queen by moving to e2. But the square e2 is occupied by her own queen, but Black could take. Wait, but the original position is White to move and in check. After White plays Qe2, the queen is on e2. The Black queen is on e7, which can move down to e2 and capture the White queen. However, White's queen would be captured if not defended. So is Qe2 defended? Let's check the White pieces. The queen is on d1 (from the FEN). If she moves to e2, is she defended? The queen is on d1, moving to e2. White's pawns on d2 are still present, but the bishop on f1 could perhaps get to e2, but after the queen moves. Wait, in the current position, the queen is on d1. To move to e2, the queen's path is d1 to e2, which is one square forward and right. So Qe2 is a valid move. But once she's there, the Black queen on e7 could attack it, but the Black queen needs to move. Unless Black has another move, but in this case, we are evaluating White's best move out of check. Wait, the current state is that White is in check, so they have to play a move that addresses the check. So the question is, which of the legal moves is best for White here.

So the possible interpositions are Qe2, Be2, Ne2, Ne4, Ne5. Which is the best?

Qe2 would place the queen on e2, but then Black can recapture the queen with their queen. Since capturing with the queen would put her in front of the king, but Black can't do that because their queen is already active. Alternatively, maybe there's a better tactical option.

Alternatively, moving a bishop to e2 (Be2) would place the bishop there. The queen is on e7, attacking e2. If Black's queen captures the bishop, they get a bishop. But in the original position, the Black queen is on e7. Capturing a piece on e2 would be possible. However, if White is in check, moving a bishop to e2 is a valid interposition. Then, after 1. Be2, the Black queen can't take the bishop unless allowed. Wait, if White moves Be2, Black can respond with Qxe2, which is a capture. But for White, the priority is to get out of check, so interposing one of the pieces is the move.

Similarly, moving the knight to e2 (Ne2) would also interpose. Now, what's best? It depends on which piece is more valuable to keep. Qe2 is queen moving to e2, which is two squares from the king. If the White queen is at e2, the Black queen on e7 could come down to e2 to capture. But developing the queen to e2 might not be as good long-term, but it's a very active square. However, if Black captures the queen, White loses it. So is the queen protected? The queen is moving from d1. When she moves to e2, she is not protected by any other piece, as the king is on e1. So if White plays Qe2, the Black queen can capture it immediately, which would relieve the check. Wait, but if the queen is on e2, capturing it would take her out of the line of attack. Wait, no—if Black captures the queen on e2, the check is still not blocked. The queen was on e2 (blocking the e-file). If the queen is captured (by Black's queen), that would be Qxe2, which would mean the queen is taking the bishop or piece on e2. But in that case, the check would still be on if the path is clear. Wait, no, because White's queen is on e2, so Black can't take with their queen. If Black captures the White queen, which is on e2, then they would be moving their queen to e2, but if the original check is still there. Wait, the check is from the Black queen on e7 to White's king on e1 via the e-file. If White interposes with Qe2, the queen is on e2. Now, the Black queen is on e7. If Black captures the queen with their own queen, they would move to e2, but this is after White has moved their queen to e2. Wait, that's a capture, not a check. So after 1. Qe2, Black can reply with Qxe2. But during White's move, they have to get out of check first. Once the queen is on e2, Black can capture it, but the check was already addressed by the interposition. However, in the position after White plays Qe2, the check is blocked, so it's a legal move. Then Black can choose to recapture. So Qe2 is a possible move, but may be followed by Qxe2, which is a draw in material. However, maybe there's another factor here.

Alternatively, Be2: the bishop moves from f1 to e2. Blocking the check. The Black queen can then take the bishop with Qxe2, but that would end the check. So White would lose a bishop but the check is addressed. Which is better: losing a queen or a bishop? Well, if the queen is captured, it's a big loss. But if the bishop is captured, the queen on e2 is gone but a bishop is lost. So which is better?

Wait, when in check, the move must address the check. So all the listed moves are candidates. Let's evaluate: if White moves the queen to e2 (Qe2), Black can take it, but after that, their queen is on e2, which is attacked by the bishop if not protected. But after Qe2, the check is already stopped. Then Black's queen can move to e2 and take the queen, but that's allowed. However, the problem here is that the queen is exchanging for the queen, but since Black's queen is capturing White's queen, it's a swap but with equal material. Wait, but the queen on d1 is moving to e2. If Black takes it with Qxe2, it's a trade of queen for queen. That's a big equal exchange, but maybe White is in time pressure, but the queen is more active. But since the king was in check, and the move is required to stop it, interposing might lead to a forced exchange. But maybe the Be2 is better because it's a less valuable piece interposing.

So if White plays Be2, then Black can take the bishop, but maybe that's a good trade. The bishop is worth 3 points, the queen is 9. So if White blocks with the bishop, then Black can take it and the check is gone. However, if White blocks with the queen, Black can take, but it's a quique exchange. However, the original position was the queen on e7 and White's queen on d1. After Qe2, the queen is at e2, and Black could take it with their queen. Then White's king is out of check. 

But the problem is that the move Be2 (blocking with the bishop) would allow Black to take the bishop and then White's king is out of check. Then, after Be2 Qxe2, White gets back into the game. However, if White plays Qe2, the response is Qxe2, but that removes a lot of material. 

Alternatively, maybe the best move is Be2. Let's think: moving the bishop from f1 to e2, blocking the check, and the bishop is now active. The queen on e7 can't attack the king anymore because the bishop is on e2. After Be2, is there another check? Let me see if the bishop move is safe. The Black queen is on e7. If the bishop is on e2, the Black queen could move to d8, but that's not checking. Alternatively, maybe after Be2, the Black queen can't move because of other checks. Wait, the Black queen is on e7. If the White bishop is on e2, the queen could be captured. So after 1. Be2 Qxe2, but the queen is on e7, if she takes the bishop on e2, that would be Qxe2. Then the check is gone, but the queen is still on the board. Then White would have to capture her or move their king. However, the White king is on e1. If Black's queen takes the bishop on e2, then she is on e2. The king is on e1. Qxe2 would put the queen on e2, which is in front of the king, but the check is no longer from that queen because the White king is on e1, which is on the e-file. Wait, if Black captures the bishop on e2 with their queen, then the queen is now at e2. The White king is at e1. The queen on e2 is directly adjacent to the king (since king is at e1, queen at e2 is one square away. But in that case, the queen attacking the king. Wait, no. The queen on e2 is attacking the king on e1 via the same file. But the king is on e1. So if the queen is on e2, that's a check. Therefore, Qxe2 would be a check, so White's move of Be2 would allow Black to capture with Qxe2+, which is a check. Therefore, White's king is back in check after that move. Wait, that's a problem. Let's clarify:

If White plays Be2, moving the bishop to e2. The king is on e1. The Black queen is on e7. If Black captures the bishop on e2 with Qxe2+, that puts the queen on e2, which is adjacent to the White king on e1. That is a check. But White's king was on e1, so they can't have a piece between the king and queen. But since the king is already on e1, if the queen is on e2, it's attacking the king, so it's a check. Therefore, the White's move Be2 is not legal because it would allow Black to recapture with a check. But wait, when White is in check, their move must get the king out of check. If they interpose a piece, the resulting position must not leave their king in check. Let's see: After White plays Be2, the king is still on e1. The Black queen is on e7. So the check is not ongoing because the bishop is on e2. So White is no longer in check from e7. Then Black can make any legal move. If Black's best reply is Qxe2+, that would be a different check. But White's king is on e1, and Black's queen to e2 would be giving check. However, that's after White's move Be2. Therefore, the move Be2 is legal because it stops the current check, but Black can then respond with Qxe2+, putting the king in check again. Wait, but if White moves the bishop to e2, the check is removed. But then Black's queen capturing the bishop on e2 would give a new check. So the move Be2 is invalid as it would leave the king in check after the move. Wait, no. The move is only invalid if after the move, the king is still in check. When White plays Be2, the bishop is now on e2, which is between the Black queen (e7) and the king (e1). So the queen on e7 is no longer giving check because the line is blocked. Therefore, the move Be2 is valid. Then Black can respond with Qxe2+, but that's a different move. So the issue is whether the interposition move is valid. For Be2: the bishop moves from f1 to e2. The king is on e1. Moving the bishop from f1 to e2 is on the same diagonal, but when moving, the king is not in front. Wait, the bishop moves from f1 to e2. The king is on e1, which is the next square behind. Let me check if this move leaves the king in check. The king is on e1. The bishop is now on e2. The Black queen is on e7. The bishop is blocking the e-file from the queen. So the king is no longer in check. Therefore, Be2 is a legal move to block the check. Then Black's queen can take the bishop, but that's a different check.

Wait, no—if the bishop is on e2, then Qxe2 would mean the queen is on e2. So the queen and king are adjacent. That's a check. So after Be2, if Black responds with Qxe2, then White's king is in check again, so that's an illegal position for White. Therefore, White can't make the move Be2 because Black's reply Qxe2 would put the king in check, which isn't allowed. Wait, but in the rules, any check by Black after White moves is fine. The only requirement is that the move removes the current check. The move Be2 would block the check from e7 to e1, so the king is out of check. Black's next move is allowed to put the king in check. So the move Be2 is valid for White. But why is it in the legal moves? The user provided the legal moves as [Ne5, Ne4, Ne2, Qe2, Be2]. So those are all valid in the current position. 

Now, the key is which of these moves is the best. Let's look at each:

1. Ne5: The knight moves from c3 to e5. That would block the queen's line. The queen is on e7, and a knight on e5 would be in the way. So this move is also valid. The knight now on e5 attacks the f7 square. But how about other checks? After Ne5, the king is not in check anymore. Then Black has options. Maybe better than other moves.

2. Ne4: Moves knight to e4, blocking the e-file. That leads to better development. The knight at e4 is attacking the f2 square (a potential target) and develops the knight to a central square.

3. Ne2: The knight moves to e2, blocking directly in front of the king. That might be safe but less strategically good. The knight is developed but perhaps not as active.

4. Qe2: Queen interposes. The queen is developed into a powerful square. But Black can recapture with Q xe2, leading to a forced exchange. If that's the case, then Qe2 might be too risky unless there's a tactical benefit.

5. Be2: Bishop moves to e2, as discussed. If Black can respond with Q xe2+, which then puts the king in check again. But that's a different check. However, after Be2, the king is safe. If Black's queen captures on e2, it's a check, but that's not a blunder. Let me see the potential responses.

Let me check: After 1. Be2, the Black queen is on e7. If White plays Be2, the check is blocked. Then Black can play Qxe2#. Let me confirm. After Be2, the king is on e1. Black's queen is on e7. They can go to e2 (Qxe2), attacking the king. However, the king is on e1. If the queen is at e2, the king is in check along the e-file. The king can't move to e2 is occupied. So he can move to e1 (no, can't stay in check), so the king on e1 is in check from Qxe2. Therefore, Qxe2 is not a checkmate because White's king can move to d1 or take the queen. Wait, if Black's queen is on e2, and the king is on e1. The king can capture the queen (Kxe2) if safe. However, if White's king is on e1, and Black's king is on e8, but that's not stopping White from Kxe2. So after Be2 and Qxe2, White can take the queen (Kxe2), which would be safe if there are no other checks. Let me check: If White takes the queen with Kxe2, then Black's queen is gone, and they have no other pieces attacking the king. So it's a valid move. Therefore, after Be2, the Black queen could take the bishop, and then the White king can take her. So resulting in a trade of queen and bishop for a king and queen. Wait, no. If White moves Be2, then Black captures the queen on e2 with their queen. Then the White king (e1) is in check from the queen on e2. But the king can capture the queen (Kxe2) only if it's legal. After Kxe2, the king would be on e2, which is attacked by Black's queen. Wait, the queen was moved to e2 by Black, so the White king taking on e2 would be into check by Black's queen. Therefore, Kxe2 is not a legal move for White. Because after that, the White king is at e2, which is under attack by Black's queen on e7? Wait no, the queen is now on e2. Wait, after Black's queen takes the bishop on e2 (Qxe2), she is on e2. Then White's king is on e1. The queen on e2 can attack the king. Therefore, White can't take the queen with Kxe2 because it would be moving into check. Alternatively, the king could move to d1 or f1. If the king is on e1 and the queen is on e2, the king can move to d1 or f1. So Kd1 or Kf1. But maybe Black can continue. So the sequence is:

White 1. Be2. Now, Black to move. They can play Qxe2, which is a capture. The bishop is captured. After that, the king is on e1. Then Black's queen is on e2. Now, if White takes the queen (impossible directly), they have to move king. So if Black's queen is on e2, White's king is in check. So White can respond by moving the king. But how? KxQ would put the king on e2, which is attacked by their own queen. So they can't do that. So they have to move the king. They can move to f1, for example. But then Black's queen can attack f1 with Qf1#. Wait, no. If the Black queen is on e2, can she move to f1 directly? Qf1 would be a different move. So if White moves king to f1, the queen on e2 can attack f1 (`;

export const MOCK_RESPONSE_REASONING = `<think>
We are at the very start of the game. White to move. Legal moves are the standard 20 opening moves: pawn moves on the 2nd rank (a3,a4,b3,b4,c3,c4,d3,d4,e3,e4,f3,f4,g3,g4,h3,h4) and knight moves (Na3, Nc3, Nf3, Nh3).

Priorities for opening moves:
1. Control the center (with pawns or pieces)
2. Develop pieces (especially knights and bishops, then king safety via castling)
3. King safety (so avoid moving pawns in front of king unnecessarily early)

Common principles:
- e4 and d4 are the most popular first moves because they stake a claim in the center.
- Nf3 is also very common because it develops a knight toward the center and prepares kingside castling.

Looking at the board: It's the starting position. All pieces are at home.

Analysis of the best move:
- e4: This is one of the most popular first moves. It controls d5 and f5, opens lines for the queen and the light-squared bishop, and is very central. It's a classic aggressive move that aims for immediate center control.
- d4: Similarly strong, controlling e5 and c5, and also very central.
- Nf3: Develops a knight, attacks the center (e5 and g5), and doesn't block the pawn structure. It's a flexible move that often leads to many openings.

Why e4 or d4 over others?
- They directly fight for central squares (d4 and e4 are the absolute center). 
- Other pawn moves (like c4, f4) are less central or weaken the king's position (f4 is the "Barnes Opening" but can be risky because it moves the f-pawn which weakens the king's shelter).

Among e4 and d4, both are excellent. However, e4 is the most traditional and is considered by many to be the best first move because it opens two diagonals (for the queen and bishop) and fights for d5 and f5.

Considering the evaluation checklist:
- Material: balanced, no material change yet.
- King safety: early stage, but e4 doesn't weaken king safety (unlike f4 or g4).
- Tactics: no immediate tactics since it's the first move.
- Position: e4 controls central squares, promotes piece development.
- Strategy: Follows opening principles of center control and development.

Confidence: 95 (because e4 is a highly recommended and common choice at all levels, but note that d4 and Nf3 are also very strong so it's not 100 - but for the purpose of this response, since we must choose one, and e4 is a top choice, high confidence is warranted).

Reasoning must be brief and under 100 words.

Reasoning for e4: "e4 immediately controls central squares (d5, f5), opens diagonals for queen and bishop, and follows classical opening principles. It's the most popular and aggressive first move that supports rapid development."

Confidence score: 95 (not 100 because there are other strong moves like d4 or Nf3, but e4 is widely regarded as the best).

Check the legal moves: e4 is in the list.

Alternative: Some might argue for d4, but e4 is equally valid and also very standard. However, the reasoning for e4 is solid.

But note: The problem says "Move 1 (White to move)" and the board is the starting position.

Given the above, I choose e4.

Reasoning word count: "e4 immediately controls central squares (d5, f5), opens diagonals for queen and bishop, and follows classical opening principles. It's the most popular and aggressive first move that supports rapid development." -> 25 words.

Confidence: 95.

Therefore, the JSON should be:
{
  "move": "e4",
  "reasoning": "e4 immediately controls central squares (d5, f5), opens diagonals for queen and bishop, and follows classical opening principles. It's the most popular and aggressive first move that supports rapid development.",
  "confidence": 95
}
</think>

{"move": "e4", "reasoning": "e4 immediately controls central squares d5/f5, opens diagonals for queen/bishop, and follows key opening principles of center dominance and rapid development. This aggressive first move gains space and supports future castling while avoiding premature pawn weaknesses.", "confidence": 95}`;
