export const LITE_MODELS = [
  "mistral/ministral-3b",
  "mistral/ministral-8b",
  "amazon/nova-micro",
  "mistral/pixtral-12b",
  "amazon/nova-lite",
  "alibaba/qwen-3-14b",
  "google/gemini-2.0-flash-lite",
  "mistral/mistral-small",
  "openai/gpt-4.1-nano",
  "openai/gpt-oss-20b",
  "google/gemini-2.5-flash-lite",
  "openai/gpt-5-nano",
  "xai/grok-3-mini",
  "alibaba/qwen-3-32b",
  "meta/llama-4-scout",
  "cohere/command-r",
  "google/gemini-2.0-flash",
  "openai/gpt-4o-mini",
  "openai/gpt-oss-120b",
  "meta/llama-4-maverick",
  "mistral/codestral",
  "meta/llama-3.3-70b",
  "deepseek/deepseek-v3",
] as const;

export const PRO_MODELS = [
  "inception/mercury-coder-small",
  "perplexity/sonar",
  "zai/glm-4.5-air",
  "mistral/mixtral-8x22b-instruct",
  "morph/morph-v3-fast",
  "anthropic/claude-3-haiku",
  "deepseek/deepseek-v3.1-base",
  "deepseek/deepseek-v3.1",
  "alibaba/qwen-3-235b",
  "mistral/magistral-small",
  "openai/gpt-4.1-mini",
  "zai/glm-4.5v",
  "morph/morph-v3-large",
  "openai/gpt-5-mini",
  "zai/glm-4.5",
  "alibaba/qwen3-coder",
  "google/gemini-2.5-flash",
  "moonshotai/kimi-k2",
  "amazon/nova-pro",
  "anthropic/claude-3.5-haiku",
  "xai/grok-3-mini-fast",
  "openai/o3-mini",
  "openai/o4-mini",
  "mistral/magistral-medium",
  "perplexity/sonar-reasoning",
  "mistral/pixtral-large",
  "mistral/mistral-large",
  "openai/gpt-4.1",
  "perplexity/sonar-reasoning-pro",
  "cohere/command-a",
  "cohere/command-r-plus",
  "google/gemini-2.5-pro",
  "openai/gpt-4o",
  "xai/grok-2",
] as const;

export const PRIME_MODELS = [
  "openai/gpt-5",
  "openai/o3",
  "perplexity/sonar-pro",
  "vercel/v0-1.0-md",
  "vercel/v0-1.5-md",
  "xai/grok-3",
  "xai/grok-4",
  "anthropic/claude-3.5-sonnet",
  "anthropic/claude-3.7-sonnet",
  "anthropic/claude-sonnet-4",
  "xai/grok-3-fast",
  "openai/o1",
  "anthropic/claude-3-opus",
  "anthropic/claude-opus-4.1",
  "anthropic/claude-opus-4",
  "alibaba/qwen-3-30b",
  "mistral/devstral-small",
] as const;

export const MODELS = [...LITE_MODELS, ...PRO_MODELS, ...PRIME_MODELS] as const;

export type Model = (typeof MODELS)[number];
