import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import CrtToggle from "@/components/crt-toggle";

import MergeOnSignin from "./merge-client";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          {/* Prevent flicker on first paint by applying stored preference ASAP */}
          <script
            // biome-ignore lint/security/noDangerouslySetInnerHtml: works!
            dangerouslySetInnerHTML={{
              __html: `try{if(localStorage.getItem('crt-disabled')==='1'){document.documentElement.classList.add('no-crt')}}catch(e){}`,
            }}
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <MergeOnSignin />
          <NuqsAdapter>{children}</NuqsAdapter>
          <CrtToggle />
        </body>
      </html>
    </ClerkProvider>
  );
}
