import type { Metadata } from "next";
import { Geist_Mono, Oxanium } from "next/font/google";
import "./globals.css";

import { ClerkProvider } from "@clerk/nextjs";
import { NuqsAdapter } from "nuqs/adapters/next/app";

import CrtToggle from "@/components/crt-toggle";
import { Navbar } from "@/components/navbar";
import { Providers } from "@/components/providers";
import { Toaster } from "@/components/ui/sonner";

import MergeOnSignin from "./merge-client";

const geistSans = Oxanium({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" suppressHydrationWarning>
        <head>
          {/* Prevent flicker on first paint by applying stored preference ASAP */}
          <script
            // biome-ignore lint/security/noDangerouslySetInnerHtml: works!
            dangerouslySetInnerHTML={{
              __html: `try{if(localStorage.getItem('crt-disabled')==='1'){document.documentElement.classList.add('no-crt')}}catch(e){}`,
            }}
          />
        </head>
        <body
          className={`${geistSans.variable} ${geistMono.variable} font-sans antialiased flex flex-col min-h-screen`}
        >
          <Providers>
            <MergeOnSignin />
            <Navbar />
            <main className="flex-1">
              <NuqsAdapter>{children}</NuqsAdapter>
            </main>
            <CrtToggle />
            <Toaster />
          </Providers>
        </body>
      </html>
    </ClerkProvider>
  );
}
